### ISSUE TITLE
Export DataFile

### ISSUE THREAD

**Issue by jmllorens** [nextnanopy/nextnanopy#6]
Is it possible to export a `DataFile` into the same or a different file format? Suppose that after loading a data file with some results, one would be interested in modifying the data and exporting it back. Something like this:
```
datafile_2d = nn.DataFile('bandedges_2d.fld', product='nextnano++')
datafile_2d['Gamma'].value = datafile_2d['Gamma'].value +1.5
datafile_2d.dump(filename='bandedges_2d_shifted.vtr', format='VTKAscii')
```

**Comment by HeorhiiY** [comment]
Hi @jmllorens !

Unfortunately, exporting DataFile is not supported yet. We will work on it and let you now once the feature is ready. Feel free to share any code and/or your implementation of the feature if you have one.


FYI: to modify the data in your example, one has to use
`datafile_2d**.variables**['Gamma'].value = datafile_2d**.variables**['Gamma'].value +1.5`

Kind regards,
Heorhii

**Comment by HeorhiiY** [comment]
Hi @jmllorens !

Exporting of datafiles is now available in nextnanopy.
Example of useage:

```
datafile_2d = nn.DataFile('bandedges_2d.fld', product='nextnano++')
datafile_2d['Gamma'].value = datafile_2d['Gamma'].value +1.5
datafile_2d.save(filename='bandedges_2d_shifted.vtr', format='VTKAscii')
```
Supported formats for saving are "dat", "VTKAscii", "AvsAscii_one_file". "dat" is only for 1D datafiles, "VTKAscii" and "AvsAscii" are for 2D and 3D datafiles. Saving the output in binary will be added later.

Kind regards,
Heorhii

**Comment by jmllorens** [comment]
Hi @HeorhiiY,

Really happy to see that this feature is implemented. 

Thanks a lot!

José.
